version: '3.9'

services:
  frontend:
    image: cookbook-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_IP: ${REACT_APP_IP}
        REACT_APP_PORT: ${REACT_APP_PORT}
        REACT_APP_API_PORT: ${REACT_APP_API_PORT}
    ports:
      - "${REACT_APP_PORT}:80"
    environment:
      - REACT_APP_IP=${REACT_APP_IP}
      - REACT_APP_PORT=${REACT_APP_PORT}
      - REACT_APP_API_PORT=${REACT_APP_API_PORT}

  backend:
    image: cookbook-backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "${REACT_APP_API_PORT}:${REACT_APP_API_PORT}"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - SPOONACULAR_API=${SPOONACULAR_API}
      - JWT_SECRET=${JWT_SECRET}
